"""initial_schema

Revision ID: 6537f2b2387a
Revises: 
Create Date: 2026-04-25 21:54:19.225974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6537f2b2387a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_operations_code')
    )
    op.create_index('ix_operations_code', 'operations', ['code'], unique=False)
    op.create_index('ix_operations_name', 'operations', ['name'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('hire_date', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('employee_id', name='uq_operators_employee_id')
    )
    op.create_index('ix_operators_employee_id', 'operators', ['employee_id'], unique=False)
    op.create_index('ix_operators_name', 'operators', ['name'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_operation_id', 'assignments', ['operation_id'], unique=False)
    op.create_index('ix_assignments_operator_id', 'assignments', ['operator_id'], unique=False)
    op.create_index('ix_assignments_status', 'assignments', ['status'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('certified_at', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skills_name', 'skills', ['name'], unique=False)
    op.create_index('ix_skills_operator_id', 'skills', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skills_operator_id', table_name='skills')
    op.drop_index('ix_skills_name', table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_assignments_status', table_name='assignments')
    op.drop_index('ix_assignments_operator_id', table_name='assignments')
    op.drop_index('ix_assignments_operation_id', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_operators_name', table_name='operators')
    op.drop_index('ix_operators_employee_id', table_name='operators')
    op.drop_table('operators')
    op.drop_index('ix_operations_name', table_name='operations')
    op.drop_index('ix_operations_code', table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
