"""Pydantic schemas for the Insights API."""

from pydantic import BaseModel, Field


class OperationFragility(BaseModel):
    """
    Fragility assessment for a single operation.

    An operation is considered fragile when fewer than 3 operators meet the
    minimum competency threshold, creating a single-point-of-failure risk.
    """

    operation_id: int
    operation_name: str
    line: str
    criticality: int
    qualified_operators_count: int
    operators_above_threshold: list[dict]
    risk_level: str = Field(
        ...,
        description="CRITIQUE | ÉLEVÉ | MOYEN | OK",
    )


class LearningPath(BaseModel):
    """
    A recommended training path for an operator to qualify on a target operation.

    Generated by identifying operators who are competent on adjacent operations
    (high similarity score) but have never practiced the target.
    """

    operator_id: int
    operator_name: str
    target_operation_id: int
    target_operation_name: str
    estimated_weeks_to_qualify: float = Field(
        ..., description="Estimated training weeks based on similarity and learning rate"
    )
    current_adjacent_score: float = Field(
        ..., ge=0, le=100, description="Effective mastery on the most similar operation"
    )
    recommended_priority: str = Field(
        ..., description="HIGH | MEDIUM | LOW based on operation criticality and gap"
    )


class InsightsResponse(BaseModel):
    """Aggregated strategic insights dashboard payload."""

    fragile_operations: list[OperationFragility]
    learning_paths: list[LearningPath]
    total_operators: int
    polyvalence_index: float = Field(
        ...,
        description="Average number of operations per operator above the competency threshold",
    )
